load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "portal",
    srcs = ["UserPortal.java"],
    main_class = "com.server.UserPortal",
    deps = ["//src/main/java/com/proto:common_java_proto"],
)
