load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "admin_portal",
    srcs = ["AdminPortal.java"],
    main_class = "com.server.AdminPortal",
    deps = ["//src/main/java/com/proto:common_java_proto"],
)
